### PR TITLE
fix: issue where typedoc docs would only show full docs for w3up-client

### PR DESCRIPTION
**Pull request by gobengo**
…and not other packages

Motivation:
* https://github.com/web3-storage/w3up/issues/1139

Rationale:
* I think it is my fault from March when I moved w3up-client into this monorepo
* The monorepo root `tsconfig.json` uses `"entryPointStrategy": "packages"`, which requires each subpackage to have its own `tsconfig.json` `"typedocOptions": {
    "entryPoints": ["./src"]
  }`
  * I missed this last time.

### CODE REVIEW

**Review by olizilla — APPROVED** [review]
This looks good to me. Do the docs build with this change? Can you publish them to CF / ipfs from ci? Then we can link to them from the docs site.

**Comment by olizilla** [comment]
These tasks were originally used by the w3up-docs repo as part of its build process. I'm thinking we could just have this repo deploy its own reference docs from ci and link to it from the docs site.

**Comment by gobengo** [comment]
@olizilla Yes they are deployed via https://github.com/web3-storage/w3up/blob/main/.github/workflows/release.yml#L51 (post release please)

**Comment by gobengo** [comment]
I can adjust the deploy however you want @olizilla slack me or assign me another issue. You probably will approve this too https://github.com/web3-storage/w3up/pull/1140

**Comment by gobengo** [comment]
fixed https://web3-storage.github.io/w3up/modules/_web3_storage_capabilities.html

**Pull request merged**
