### PR TITLE
feat: In-Memory Driver

### PR DESCRIPTION
**Pull request by apetta**
Adding an in-memory driver for use in serverless environments

### CODE REVIEW

**Comment by apetta** [comment]
Thanks for pointing that out @travis! I've made the changes and tried to build it locally, ran without errors. Lmk if it looks okay to you!

**Comment by apetta** [comment]
@travis did I miss something again? Can't make sense of the [error](https://github.com/web3-storage/w3up/actions/runs/5718341511/job/15562011930?pr=847)

**Comment by travis** [comment]
Ah looks like the code style doesn't match our `prettier` configs - from the root of the repo you should be able to run `pnpm format` and it should fix whatever's out of sync. 

You can verify the code is formatted correctly by running `pnpm lint` from the root of the repo - if it looks clean then check in whatever has changed and push it up to this branch!

Thanks!

**Comment by apetta** [comment]
Apologies for making a meal of this lol, all done now hopefully!

**Review by travis — APPROVED** [review]

**Pull request merged**
